### ISSUE TITLE
TypeError from Anaconda python 3.7?

### ISSUE THREAD

**Issue by theresetbutton** [facebookresearch/open_lth#22]
hey everyone. I'm quite new to this, so this maybe me.... but...

system: ryzen 3600 - rtx3060 12gb - Windows 10 - Anaconda3.

Env: Python 3.7 - Pytorch - torchvision.

Error Dump:

(openlth) C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth>python open_lth.py
Traceback (most recent call last):
  File "open_lth.py", line 9, in <module>
    from cli import runner_registry
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth\cli\runner_registry.py", line 7, in <module>
    from lottery.branch.runner import BranchRunner
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth\lottery\branch\runner.py", line 12, in <module>
    from lottery.branch import registry
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth\lottery\branch\registry.py", line 6, in <module>
    from lottery.branch.base import Branch
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth\lottery\branch\base.py", line 12, in <module>
    from cli import shared_args
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth\cli\shared_args.py", line 10, in <module>
    import models.registry
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth\models\registry.py", line 11, in <module>
    from models import cifar_resnet, cifar_vgg, mnist_lenet, imagenet_resnet
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth\models\cifar_resnet.py", line 10, in <module>
    from lottery.desc import LotteryDesc
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth\lottery\desc.py", line 18, in <module>
    import pruning.registry
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth\pruning\registry.py", line 10, in <module>
    from pruning import sparse_global
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth\pruning\sparse_global.py", line 10, in <module>
    import models.base
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\open_lth\models\base.py", line 101, in <module>
    class DistributedDataParallel(Model, torch.nn.parallel.DistributedDataParallel):
  File "C:\Users\TheResetButton\anaconda3\envs\openlth\lib\abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases ABC, Module

So if I'm looking at this right, I'm looking at ../lib/abc.py? this was from python 3.7 setup, and not from the project? is this an error that got fixed in later versions of python? I also havent setup my output directories yet.. I dont see anything like that mentioned above. any help would be awesome..... and yes, I would love to use this under linux, but that mean moving my rtx3060 to my downstairs box... and losing out on using it on my main rig.

**Comment by yuuma002** [comment]
Same issue.
